# Blueprint de Render para desplegar la app con Docker
# Docs: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: u-la-salle-contact
    runtime: docker        # Ejecuta con tu Dockerfile
    plan: free             # Free tier: sin discos persistentes
    region: oregon
    autoDeploy: true
    dockerCommand: ""      # Usa CMD del Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: DB_FILE
        value: /data/contacts.db
    # IMPORTANTE (free tier): No se puede usar 'disk'. El archivo SQLite en /data será EFÍMERO.
    # Cada redeploy / apagado prolongado puede recrear la base. Si necesitas persistencia -> upgrade + agregar 'disk'.
    healthCheckPath: /api/health
